services:
  db-postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-list
    command: >
      postgres
      -c idle_in_transaction_session_timeout=60000
      -c statement_timeout=6000
      -c max_connections=200
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
