services:
  scylla-node1:
    image: scylladb/scylla:2025.1.3
    container_name: scylla-node1
    ports:
      - "9042:9042"
      - "9160:9160"
      - "10000:10000"
    command: --seeds=scylla-node1 --smp=1 --memory=750M --overprovisioned=1 --api-address=0.0.0.0 --listen-address=0.0.0.0 --rpc-address=0.0.0.0 --broadcast-address=scylla-node1 --broadcast-rpc-address=scylla-node1 --endpoint-snitch=GossipingPropertyFileSnitch
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
  scylla-node2:
    image: scylladb/scylla:2025.1.3
    container_name: scylla-node2
    ports:
      - "9043:9042"
      - "9161:9160"
      - "10001:10000"
    command: --seeds=scylla-node1 --smp=1 --memory=750M --overprovisioned=1 --api-address=0.0.0.0 --listen-address=0.0.0.0 --rpc-address=0.0.0.0 --broadcast-address=scylla-node2 --broadcast-rpc-address=scylla-node2 --endpoint-snitch=GossipingPropertyFileSnitch
    networks:
      - scylla-net
    depends_on:
      scylla-node1:
        condition: service_healthy
    volumes:
      - ./cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties

  scylla-node3:
    image: scylladb/scylla:2025.1.3
    container_name: scylla-node3
    ports:
      - "9044:9042"
      - "9162:9160"
      - "10002:10000"
    command: --seeds=scylla-node1 --smp=1 --memory=750M --overprovisioned=1 --api-address=0.0.0.0 --listen-address=0.0.0.0 --rpc-address=0.0.0.0 --broadcast-address=scylla-node3 --broadcast-rpc-address=scylla-node3 --endpoint-snitch=GossipingPropertyFileSnitch
    networks:
      - scylla-net
    depends_on:
      scylla-node1:
        condition: service_healthy
    volumes:
      - ./cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
networks:
  scylla-net:
